- name: Set WAN 
  uri:
    url: "{{ opnsense_host }}/interface/set"
    method: POST
    user: "{{ api_key }}"
    password: "{{ api_secret }}"
    headers:
      Content-Type: "application/json"
    body:
      {
        "interface": "wan",  
        "enabled": "1",      
        "type": "dhcp",      
        "dhcp": "1"          
      }
    body_format: json
    validate_certs: no
    status_code: 200
    register: result

- name: Set OPT1
  uri:
    url: "{{ opnsense_url }}/interface/set"
    method: POST
    user: "{{ api_key }}"
    password: "{{ api_secret }}"
    headers:
      Content-Type: "application/json"
    body:
      {
        "interface": "lan",        
        "enabled": "1",            
        "type": "static",          
        "ipaddr": "192.168.1.1",   
        "subnet": "24",            
        "gateway": "192.168.1.254" 
      }
    body_format: json
    validate_certs: no
    status_code: 200
    register: result_lan