- name: Set IP addresses
  vyos_config:
    lines:
      - set interfaces ethernet eth0 address 192.168.5.15/24
      - set interfaces ethernet eth1 address 192.168.7.1/24
      - set interfaces ethernet eth2 address 192.168.6.1/24
    save: true

- name: assign zones
  vyos_config:
    lines:
      - set firewall zone LAN member interface eth2
      - set firewall zone OPNSENSE member interface eth0
      - set firewall zone ADMIN member interface eth1
    save: true

- name: Set WAN/default route to Opnsense
  vyos_config:
    lines:
      - set protocols static route 0.0.0.0/0 next-hop 192.168.5.1
      - set nat source rule 100 description 'Masquerade admin requests to WAN'
      - set nat source rule 100 source address '192.168.7.0/24'
      - set nat source rule 100 outbound-interface name eth0
      - set nat source rule 100 translation address masquerade

      - set nat source rule 100 description 'Masquerade vlans requests to WAN'
      - set nat source rule 100 source address '192.168.6.0/24'
      - set nat source rule 100 outbound-interface name eth0
      - set nat source rule 100 translation address masquerade
    save: true

