- name: DHCP for vlans
  vyos_config:
    lines:
      - set service dhcp-server shared-network-name LAN subnet 192.168.6.0/24 default-router 192.168.6.1
      - set service dhcp-server shared-network-name LAN subnet 192.168.6.0/24 range 0 start 192.168.6.5
      - set service dhcp-server shared-network-name LAN subnet 192.168.6.0/24 range 0 stop 192.168.6.10
      - set service dhcp-server shared-network-name LAN subnet 192.168.6.0/24 dns-server 192.168.6.1
    save: true
