- name: Configure Vyos
  hosts: vyos
  connection: network_cli
  gather_facts: no
  collections:
    - vyos.vyos

  roles:
    - vyos

- name: Configure OPNsense 
  hosts: localhost
  connection: local
  gather_facts: no

  roles:
    - opnsense